[build]
  # Build command (if needed)
  command = "npm run build"
  
  # Directory to publish (current directory for static files)
  publish = "."
  
  # Functions directory for serverless functions
  functions = "netlify/functions"

# Redirects and rewrites
[[redirects]]
  # API routes should go to serverless functions
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Environment variables (set these in Netlify dashboard)
# MONGODB_URI = "your_mongodb_atlas_connection_string"
# JWT_SECRET = "your_jwt_secret"
