[build]
  # Build command
  command = "npm install"
  
  # Directory to publish (current directory for static files)
  publish = "."
  
  # Functions directory for serverless functions
  functions = "netlify/functions"

# Redirects - SPECIFIC routes FIRST
[[redirects]]
  from = "/api/tracks/upload"
  to = "/.netlify/functions/upload-track"
  status = 200
  force = true

[[redirects]]
  # Auth endpoints
  from = "/api/auth/login"
  to = "/.netlify/functions/auth-login"
  status = 200
  force = true

[[redirects]]
  from = "/api/auth/register"
  to = "/.netlify/functions/auth-register"
  status = 200
  force = true

[[redirects]]
  # Tracks endpoints - dedicated functions
  from = "/api/tracks/public"
  to = "/.netlify/functions/tracks-public"
  status = 200
  force = true

[[redirects]]
  from = "/api/tracks/my-tracks"
  to = "/.netlify/functions/tracks-my-tracks"
  status = 200
  force = true

[[redirects]]
  # User endpoints - dedicated function
  from = "/api/user/profile"
  to = "/.netlify/functions/user-profile"
  status = 200
  force = true

[[redirects]]
  # Health endpoint
  from = "/api/health"
  to = "/.netlify/functions/api-health"
  status = 200
  force = true

# GENERIC fallback - MUST be LAST API rule
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200
  force = true

# Headers for security and CORS
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# SPA fallback - ABSOLUTE LAST
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
