[build]
  # Build command
  command = "npm install"
  
  # Directory to publish (current directory for static files)
  publish = "."
  
  # Functions directory for serverless functions
  functions = "netlify/functions"

# Redirects and rewrites
[[redirects]]
  # Health endpoint - specific function
  from = "/api/health"
  to = "/.netlify/functions/api-health"
  status = 200
  force = true

[[redirects]]
  # Other API routes should go to main server function
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200
  force = true

# Headers for security and CORS
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
